school_proj/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='details'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete')
]

school_proj/school_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
urlpatterns = [
    path('', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls',namespace='basic_app'))
]

school_proj/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):

    name = models.CharField(max_length = 256)
    principal = models.CharField(max_length = 256)
    location = models.CharField(max_length = 256)

    def get_absolute_url(self):
        return reverse("basic_app:details",kwargs={'pk':self.pk})

    def __str__(self):
        return self.name

class Student(models.Model):

    name = models.CharField(max_length = 256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

school_proj/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from basic_app import models
from django.urls import reverse_lazy
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['inject_me'] = 'Injected Data'
        return context

class SchoolListView(ListView):
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_details'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    context_object_name = 'school'
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields=("name","principal")
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

school_proj/basic_app/templates/basic_app/basic_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'basic_app:list' %}">List</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
      </div>
    </nav>
    <h1> Welcome to the site </h1>
    <div class="container">
      {% block body_block%}
      {% endblock %}
    </div>
  </body>
</html>

school_proj/basic_app/templates/basic_app/school_confirm_delete.html
{%extends 'basic_app/basic_base.html' %}
{% block body_block %}
<h1> Delete {{school.namr}} ?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Delete">
  <a class='btn btn-primary 'href="{% url 'basic_app:details' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

school_proj/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_base.html' %}
{% block body_block %}
<div class="Jumbotron">
  <h2>Please find the school details</h2>
  <p>Schhol name is: {{school_details.name}} </p>
  <p>Princial is: {{school_details.principal}} </p>
  <p>Location is: {{school_details.location}} </p>

  <h2>Student details is: </h2>
  {% for student in school_details.students.all %}
  <p>Name is {{ student.name }} who is {{ student.age }} years old. </p>
  {% endfor %}

  <p><a class='btn btn-warning' href="{% url 'basic_app:update'  pk=school_details.pk %}">Update</a></p>
  <p><a class='btn btn-danger' href="{% url 'basic_app:delete'  pk=school_details.pk %}">Delete</a></p>


</div>
{% endblock %}

school_proj/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_base.html' %}
{% block body_block %}
{% if not form.instance.pk %}
  Create school
{% else %}
  Update school
{% endif %}
<div class=Jumbotron>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='create'>
  </form>
</div>
{% endblock %}

school_proj/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_base.html' %}
{% block body_block %}
<div class="Jumbotron">
  <ol>
    {% for school in school_list %}
    <h2><li><a href="{{school.id}}/"> {{ school.name }}</a></li></h2>
    {% endfor %}
  </ol>
</div>
{% endblock %}

school_proj/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'basic_app:list' %}">List</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
      </div>
    </nav>
    <h1> Welcome to the site </h1>
    <div class="container">
      {% block body_block%}
      {% endblock %}
    </div>
  </body>
</html>

school_proj/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
  <h1>This is Template class based view </h1>
  <h2>Injected Content is: {{ inject_me }} </h2>
{% endblock %}